name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Surge CLI
      run: npm install -g surge

    - name: Deploy to Surge.sh
      run: |
        surge ./ surge.sh --domain <your-custom-domain>.surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
